In [3]:
import numpy as np

## Importing the data

In [14]:
!gdown 1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF

Downloading...
From: https://drive.google.com/uc?id=1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF
To: C:\Users\vgaur\Desktop\DSML\GIT\Indeed Interview Qns Analysis\fitness.txt

  0%|          | 0.00/3.14k [00:00<?, ?B/s]
100%|##########| 3.14k/3.14k [00:00<?, ?B/s]


In [30]:
data=np.loadtxt("fitness.txt",dtype='str')

## Basic analysis

In [31]:
data[:10]

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66'],
       ['11-10-2017', '4545', '100', '149', '6', '0', '66'],
       ['12-10-2017', '4340', '100', '140', '6', '0', '66'],
       ['13-10-2017', '1230', '100', '38', '7', '0', '66'],
       ['14-10-2017', '61', '100', '1', '5', '0', '66'],
       ['15-10-2017', '1258', '100', '40', '6', '0', '65']], dtype='<U10')

In [32]:
data.shape

(96, 7)

There are 96 records and each record has 7 features.
These features are:
- Date
- Step count
- Mood
- Calories Burned
- Hours of sleep
- activity status
- weight 

In [33]:
data[0]

array(['06-10-2017', '5464', '200', '181', '5', '0', '66'], dtype='<U10')

- Each row contain every category of data, so we need to transpose it to get the all the features seperate in different variables.

In [34]:
data=data.T

In [35]:
#Now, the first column contains date, then step_count, etc. likewise.
date, step_count, mood, calories, sleep, activity, weight = data

In [36]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [37]:
step_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

#### Changing the datatypes of numerical features into int

In [38]:
step_count=np.array(step_count,dtype='int')
calories=np.array(calories,dtype='int')
sleep=np.array(sleep,dtype='int')
weight=np.array(weight,'int')

#### Changing the date : str to datetime

In [ ]:
from datetime import datetime

In [93]:
lst=list(date)
date_obj=[]
wday=[]

In [94]:
def w(day):
    w=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
    x=w[day]
    return x

In [95]:
for i in lst:
    date_temp=datetime.strptime(i,'%d-%m-%Y')
    date_obj.append(date_temp.date())
    wday.append(w(date_temp.weekday()))

day_of_week=np.array(wday)
date_obj=np.array(date_obj)


96 96
96 96


In [98]:
day_of_week

array(['Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday',
       'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday',
       'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday',
       'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday',
       'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday',
       'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
       'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday',
       'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday',
       'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday',
       'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday',
       'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday',
       'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday',
       'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
       'Friday', 'Saturday', 'Sunday', 

In [99]:
date_obj[:5]

array([datetime.date(2017, 10, 6), datetime.date(2017, 10, 7),
       datetime.date(2017, 10, 8), datetime.date(2017, 10, 9),
       datetime.date(2017, 10, 10)], dtype=object)

In [100]:
np.unique(day_of_week,return_counts=True)

(array(['Friday', 'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday',
        'Wednesday'], dtype='<U9'),
 array([14, 14, 14, 14, 14, 13, 13], dtype=int64))

In [101]:
np.unique(date_obj,return_counts=True)

(array([datetime.date(2017, 10, 6), datetime.date(2017, 10, 7),
        datetime.date(2017, 10, 8), datetime.date(2017, 10, 9),
        datetime.date(2017, 10, 10), datetime.date(2017, 10, 11),
        datetime.date(2017, 10, 12), datetime.date(2017, 10, 13),
        datetime.date(2017, 10, 14), datetime.date(2017, 10, 15),
        datetime.date(2017, 10, 16), datetime.date(2017, 10, 17),
        datetime.date(2017, 10, 18), datetime.date(2017, 10, 19),
        datetime.date(2017, 10, 20), datetime.date(2017, 10, 21),
        datetime.date(2017, 10, 22), datetime.date(2017, 10, 23),
        datetime.date(2017, 10, 24), datetime.date(2017, 10, 25),
        datetime.date(2017, 10, 26), datetime.date(2017, 10, 27),
        datetime.date(2017, 10, 28), datetime.date(2017, 10, 29),
        datetime.date(2017, 10, 30), datetime.date(2017, 10, 31),
        datetime.date(2017, 11, 1), datetime.date(2017, 11, 2),
        datetime.date(2017, 11, 3), datetime.date(2017, 11, 4),
        datetime.d

- It means there are no duplicate days are present. (**Data is present for each day**)

#### Converting mood and activity to categories

In [39]:
np.unique(mood)

array(['100', '200', '300'], dtype='<U10')

In [40]:
np.unique(mood,return_counts=True)

(array(['100', '200', '300'], dtype='<U10'), array([29, 27, 40], dtype=int64))

- So, there are three different moods.
- Categorising these mood into -> **100 : Sad, 200 : Neutral, 300 : Happy**

In [42]:
mood[mood=='100']='Sad'
mood[mood=='200']='Neutral'
mood[mood=='300']='Happy'

In [43]:
np.unique(mood,return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([40, 27, 29], dtype=int64))

In [44]:
np.unique(activity,return_counts=True)

(array(['0', '500'], dtype='<U10'), array([54, 42], dtype=int64))

- So, there are only two activity 
- We can describe: 0 as Inactive and 500 as Active

In [45]:
activity[activity=='0']='Inactive'
activity[activity=='500']='Active'

In [46]:
np.unique(activity,return_counts=True)

(array(['Active', 'Inactive'], dtype='<U10'), array([42, 54], dtype=int64))

## Finding Some Insights

#### Average Step counts

In [113]:
np.mean(step_count)

2935.9375

##### Average step count on each day of the week

In [117]:
np.mean(step_count[day_of_week=='Sunday'])

2803.4285714285716

In [115]:
w=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
mean_per_day=[]
for i in w:
    mean_per_day.append(np.mean(step_count[day_of_week==i]))
mean_per_day=np.round(mean_per_day,2)

In [116]:
mean_per_day

array([2803.43, 4299.07, 4357.92, 4371.38, 2220.36, 1817.36,  886.14])

- There is a increase of step_count from Sunday to Thursday and then decreaeses towards Saturday.

#### Max & Min Step count

In [118]:
np.max(step_count)

7422

In [125]:
day_of_week[step_count==np.max(step_count)]

array(['Wednesday'], dtype='<U9')

In [126]:
np.min(step_count)

25

In [128]:
day_of_week[step_count==np.min(step_count)]

array(['Saturday'], dtype='<U9')

### Relation between steps count, mood and activity

##### Step count and activity

In [130]:
np.mean(step_count[mood=='Sad'])

2103.0689655172414

In [131]:
np.mean(step_count[mood=='Neutral'])

3153.777777777778

In [132]:
np.mean(step_count[mood=='Happy'])

3392.725

- There is a **increase** in **average step count** as mood changes from Sad to Happy

##### Step count and activity

In [133]:
np.mean(step_count[activity=='Inactive'])

2709.8888888888887

In [134]:
np.mean(step_count[activity=='Active'])

3226.5714285714284

- There is a **jump in step_count Active days** as compared to Inactive days

## Comparing the different moods for different conditions

#### When Step_count<2000

In [142]:
len(step_count[step_count<2000])

39

In [143]:
np.unique(mood[step_count<2000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([13,  8, 18], dtype=int64))

- Out of total = 96 days, user travelled **<2000 steps** for **39 days**
- Out of 39 days, 
1. User was **Happy** : **13 times**
2. User was **Neutral** : **8 times**
3. User was **Sad** : **18 times**

#### When step_count>4000

In [144]:
len(step_count[step_count>4000])

38

In [136]:
np.unique(mood[step_count>4000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([22,  9,  7], dtype=int64))

- Out of total = 96 days, user travelled **>4000 steps** for **38 days**
- Out of 39 days, 
1. User was **Happy** : **22 times**
2. User was **Neutral** : **9 times**
3. User was **Sad** : **7 times**

- There seems to have a relationship between **mood** and **step_count**
- When the step_count<2000, 
            1. There are 49% of cases of mood being Sad.
            2. There are 33% of cases of mood being Happy.
- When the step_count>4000, 
            1. There are 59% of cases of mood being Happy.
            2. There are 20% of cases of mood being Sad.

# Insights

- There is a **increase** of step_count from **Sunday to Thursday** and then **decreaeses** towards **Saturday**.
- In case of **low step count**, 49% of mood is **Sad**.
- In case of **high step count**, 59% of mood is **Happy**.
- There is a **increase** in **average step count** as mood changes from Sad to Happy